server {
    listen 80;
    server_name localhost;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Zorgt ervoor dat React Router (als we dat ooit toevoegen) goed werkt via Nginx
        try_files $uri $uri/ /index.html;
    }
}
